// Audit logging utilities for admin actions

import { db } from "@/lib/db"

export type AuditTargetType = "post" | "club" | "user" | "leadership_request"

export interface AuditLogEntry {
  userId: string
  action: string
  targetType: AuditTargetType
  targetId?: string
  details?: string
  ipAddress?: string
}

/**
 * Log an admin action to the audit log
 */
export async function logAuditAction(entry: AuditLogEntry): Promise<void> {
  try {
    // ID is auto-generated by database
    await db.query(
      `INSERT INTO audit_log (user_id, action, target_type, target_id, details, ip_address, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)`,
      [
        entry.userId,
        entry.action,
        entry.targetType,
        entry.targetId || null,
        entry.details || null,
        entry.ipAddress || null,
      ]
    )
  } catch (error) {
    console.error("Error logging audit action:", error)
    // Don't throw - audit logging should not break the main operation
  }
}

/**
 * Get audit log entries with optional filters
 */
export async function getAuditLog(options: {
  userId?: string
  targetType?: AuditTargetType
  targetId?: string
  limit?: number
  offset?: number
}): Promise<any[]> {
  try {
    let query = `SELECT * FROM audit_log WHERE 1=1`
    const params: any[] = []
    let paramIndex = 1

    if (options.userId) {
      query += ` AND user_id = $${paramIndex}`
      params.push(options.userId)
      paramIndex++
    }

    if (options.targetType) {
      query += ` AND target_type = $${paramIndex}`
      params.push(options.targetType)
      paramIndex++
    }

    if (options.targetId) {
      query += ` AND target_id = $${paramIndex}`
      params.push(options.targetId)
      paramIndex++
    }

    query += ` ORDER BY created_at DESC`

    if (options.limit) {
      query += ` LIMIT $${paramIndex}`
      params.push(options.limit)
      paramIndex++
    }

    if (options.offset) {
      query += ` OFFSET $${paramIndex}`
      params.push(options.offset)
    }

    const result = await db.query(query, params)
    return result.rows
  } catch (error) {
    console.error("Error getting audit log:", error)
    return []
  }
}
